# -*- coding: utf-8 -*-
"""
Created on Fri Oct 22 23:41:50 2021

@author: Subha
"""
import os
import win32com.client
from datetime import date


def get_day_code(date_str):
    """
    Get Day in Specific Format

    Parameters
    ----------
    date_str : TYPE : Datetime.Date
        Date Object.

    Returns
    -------
    day_code : TYPE : String
        Day in required format.

    """
    if date_str.day in [1, 21, 31]:
        day_code = f"{str(date_str.day)}st"
    elif date_str.day in [2, 22]:
        day_code = f"{str(date_str.day)}nd"
    elif date_str.day in [3, 23]:
        day_code = f"{str(date_str.day)}rd"
    else:
        day_code = f"{str(date_str.day)}th"
    return day_code


def send_mail(date_str, root_directory):
    """
    Send Mail Function

    Parameters
    ----------
    date_str : TYPE : Date
        Date for which CRR is generated.

    root_directory : TYPE : String
        Path to the root directory
        
    Returns
    -------
    None.

    """
    outlook = win32com.client.Dispatch('outlook.application')
    Msg = outlook.CreateItem(0)
    Msg.To = "test@domain.com"

    Msg.CC = "test@domain.com"

    Msg.Subject = f"CRR Balance_{get_day_code(date_str)}\
 {date_str.strftime('%b')}-{date_str.strftime('%y')}"
    Msg.Body = f"Hi Team,\nI have uploaded the CRR balance file for\
 {get_day_code(date_str)} {date_str.strftime('%b')} in\
 AWS. Kindly provide your approval to the team to proceed for EoD once\
 uploads from your side are completed.\n\nNote: This mail has been autogenerated\
 with python and necessary logs are attached for successful process completion."

    # Add Attachment
    Msg.Attachments.Add(os.path.join(root_directory,
                                     f"crr_upload_{date.today().strftime('%d_%m_%Y')}.log"))

    # Send Mail
    Msg.Send()
